create or replace package TRN_COMPANY_API is

  function GET_COMPANY_NAME(COMPANY_ID_ IN VARCHAR2) RETURN VARCHAR2;
  function GET_COMPANY_REGNO(COMPANY_ID_ IN VARCHAR2) RETURN INT;
  function GET_COMPANY_ADDRESS(COMPANY_ID_ IN VARCHAR2) RETURN VARCHAR2;

  PROCEDURE NEW_RECORD(COMPANY_ID_   IN VARCHAR2,
                       REG_NO_       INT,
                       COMPANY_NAME_ VARCHAR2,
                       ADDRESS_      VARCHAR2);

  PROCEDURE UPDATE_RECORD(COMPANY_ID_   IN VARCHAR2,
                          REG_NO_       IN INT,
                          COMPANY_NAME_ IN VARCHAR2,
                          ADDRESS_      IN VARCHAR2);

  PROCEDURE DELETE_RECORD(COMPANY_ID_ IN VARCHAR2);

end TRN_COMPANY_API;
/
create or replace package body TRN_COMPANY_API is

  function GET_COMPANY_NAME(COMPANY_ID_ IN VARCHAR2) RETURN VARCHAR2 IS
    result VARCHAR2(100);
  
    CURSOR GET_COMP_NAME IS
      SELECT COMPANYNAME
        FROM TRN_COMPANY_TAB
       WHERE COMPANYID = COMPANY_ID_;
  BEGIN
    OPEN GET_COMP_NAME;
    FETCH GET_COMP_NAME
      INTO result;
    CLOSE GET_COMP_NAME;
  
    RETURN result;
  END GET_COMPANY_NAME;

  function GET_COMPANY_REGNO(COMPANY_ID_ IN VARCHAR2) RETURN INT IS
    result INT;
  
    CURSOR GET_COMP_REGNO IS
      SELECT REGISTRATIONNO
        FROM TRN_COMPANY_TAB
       WHERE COMPANYID = COMPANY_ID_;
  BEGIN
    OPEN GET_COMP_REGNO;
    FETCH GET_COMP_REGNO
      INTO result;
    CLOSE GET_COMP_REGNO;
  
    RETURN result;
  END GET_COMPANY_REGNO;

  function GET_COMPANY_ADDRESS(COMPANY_ID_ IN VARCHAR2) RETURN VARCHAR2 IS
    result VARCHAR2(100);
  
    CURSOR GET_COMP_ADDRESS IS
      SELECT ADDRESS FROM TRN_COMPANY_TAB WHERE COMPANYID = COMPANY_ID_;
  BEGIN
    OPEN GET_COMP_ADDRESS;
    FETCH GET_COMP_ADDRESS
      INTO result;
    CLOSE GET_COMP_ADDRESS;
  
    RETURN result;
  END GET_COMPANY_ADDRESS;

  PROCEDURE NEW_RECORD(COMPANY_ID_   IN VARCHAR2,
                       REG_NO_       IN INT,
                       COMPANY_NAME_ IN VARCHAR2,
                       ADDRESS_      IN VARCHAR2) IS
  BEGIN
    INSERT INTO TRN_COMPANY_TAB
      (COMPANYID, REGISTRATIONNO, COMPANYNAME, ADDRESS)
    VALUES
      (COMPANY_ID_, REG_NO_, COMPANY_NAME_, ADDRESS_);
  END NEW_RECORD;

  PROCEDURE UPDATE_RECORD(COMPANY_ID_   IN VARCHAR2,
                          REG_NO_       IN INT,
                          COMPANY_NAME_ IN VARCHAR2,
                          ADDRESS_      IN VARCHAR2) IS
  BEGIN
    UPDATE TRN_COMPANY_TAB
    
       SET REGISTRATIONNO = REG_NO_,
           COMPANYNAME    = COMPANY_NAME_,
           ADDRESS        = ADDRESS_
    
     WHERE COMPANYID = COMPANY_ID_;
  
  END UPDATE_RECORD;

  PROCEDURE DELETE_RECORD(COMPANY_ID_ IN VARCHAR2) IS
  BEGIN
    DELETE TRN_COMPANY_TAB WHERE COMPANYID = COMPANY_ID_;
  END DELETE_RECORD;

end TRN_COMPANY_API;
/
